// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTdQ0VTakEzYcvOqOBlTgmis-jXyph1QQ',
    appId: '1:737338660942:web:1272104aa22622c1ddcb1f',
    messagingSenderId: '737338660942',
    projectId: 'myflutterproject2-11ee4',
    authDomain: 'myflutterproject2-11ee4.firebaseapp.com',
    storageBucket: 'myflutterproject2-11ee4.firebasestorage.app',
    measurementId: 'G-TXB11MWHVL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjv3ZFMuFkL08WDPtkbA_yRtjHO3s6jsg',
    appId: '1:737338660942:android:5b5e7b6d07555702ddcb1f',
    messagingSenderId: '737338660942',
    projectId: 'myflutterproject2-11ee4',
    storageBucket: 'myflutterproject2-11ee4.firebasestorage.app',
  );
}
